//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod image_metadata;
pub mod notification;
pub mod permission;
pub mod post_metadata;
pub mod role;
pub mod role_permissions;
pub mod user;
pub mod user_roles;
